### PR TITLE
feat(page): submit page

### LINKED ISSUE #18: Submit page
I'll create a new account called csszen-stash to keep temporary themes for editing and those who has no GitHub account getting involved in.

Consider using [Broadcast Channel API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) to implement theming in two standalone tabs.

### PR DESCRIPTION
**Pull request by somarlyonks**
close #18 

TODO:

- [x] submit to gist
- [x] load from gist
- [ ] scss support
- [ ] postcss autoprefixer

### CODE REVIEW

**Comment by csszen** [comment]
@somarlyonks leave sass/postcss alone, finish the css lifetime that we can merge are preferred.

**Comment by somarlyonks** [comment]
Enhancements in issue #21 and #22

**Comment by csszen** [comment]
How do we handle the images and fonts in themes? I didn't notice some changes relative to that.

**Comment by somarlyonks** [comment]
#23 :)

**Pull request merged**
